# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         eGuideDog-Dict-Cantonese
version:      0.4
version_from: Cantonese.pm
installdirs:  site
requires:
    Encode::CNMap:                 0
    Storable:                      0
    utf8:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
